# Numpy <hr style="border:2.5px solid #15cf15ff"></hr>

<b>Gizm Ceel Cahilig</b>
<br>Computer Engineer

In [17]:
# imports and packages
import numpy as np

# 1D Array

In [18]:
my_array=[1,2,3]


In [19]:
type(my_array)

list

In [20]:
my_array = np.array([1,2,3])

In [21]:
np.shape(my_array)

(3,)

# 2D Array

In [22]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.shape(my_array)

(2, 3)

In [24]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
np.shape(my_array)

(2, 3)

In [26]:
trans_array = my_array.T

In [27]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
np.shape(trans_array)

(3, 2)

In [29]:
np.sum(trans_array, axis=0)

array([ 6, 15])

In [30]:
np.sum(trans_array, axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [31]:
resistance = np.array (
    [
        [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], # Jaguar
        [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan], # Panther
    ]
)
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [32]:
# Mean
np.mean(resistance, axis=1)

array([9.4, nan])

In [33]:
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])